site_name: Jacob DataBase Book
site_description: "Jacob's Database 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'MySQL 基础篇':
    - '第一节 基础架构：执行一条SQL查询语句' : 'chap1/1mysql_exec.md'
    - '第二节 日志系统：执行一条SQL更新语句' : 'chap1/2mysql_logs.md'
    - '第三节 事务隔离' : 'chap1/3mysql_isolaion.md'
    - '第四节 深入浅出索引' : 'chap1/4mysql_index.md'
    - '第五节 全局锁和表锁' : 'chap1/5mysql_lock.md'
    - '第六节 事务到底是隔离的还是不隔离的' : 'chap1/6mysql_transaction_isolation.md'
  - 'AWS Aurora 技术与实战教程':
    - '第一节 深入了解 Aurora 数据库' : 'aurora/1Intital_Explore.md'
    - '第二节 揭秘 Aurora 底层存储' : 'aurora/2Aurora_Adv.md'
    - '第三节 Aurora Basic Operation' : 'aurora/3Aurora_operation.md'
  - 'MySQL on K8S':
    - '第一节 Kubernetes 部署 MySQL 主从服务': 'chap_k8s/1Mysql_k8s.md'
  - 'MySQL 基础操作篇':
    - '第一节 数据库简介、及常用数据库介绍': 'db_ops/1db_intro.md'
    - '第二节 安装 MySQL Repository & Jam db install': 'db_ops/2db_install.md'
    - '第三节 结构化查询语言 SQL': 'db_ops/3db_sql.md'
  - 'Extra 知识扩展':
    - 'GitHub+Travis+Mkdocs自动化构建文档库(DataBase)' : 'extra/mkdoc_gitbook.md'

repo_url: https://github.com/Chao-Xi/jxdatabasebook.git
repo_name: "jxdatabasebook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'red'
  i18n:
    prev: 'Previous'
    next: 'Next'