site_name: Jacob DataBase Book
site_description: "Jacob's Database 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'MySQL 基础篇':
    - '第一节 基础架构：执行一条SQL查询语句' : 'chap1/1mysql_exec.md'
    - '第二节 日志系统：执行一条SQL更新语句' : 'chap1/2mysql_logs.md'
    - '第三节 事务隔离' : 'chap1/3mysql_isolaion.md'
    - '第四节 深入浅出索引' : 'chap1/4mysql_index.md'
    - '第五节 全局锁和表锁' : 'chap1/5mysql_lock.md'
    - '第六节 事务到底是隔离的还是不隔离的' : 'chap1/6mysql_transaction_isolation.md'
    - 'MySQL 基础知识复习': 'chap1/mysql_bia_review.md'
  - 'MySQL 实战篇':
    - 'L1 表结构设计篇 - 数据类型': 'chap2_opt/1table_design.md'
    - 'L2 表结构设计篇 - 表设计': 'chap2_opt/2table_design.md'
    - 'L3 索引优化': 'chap2_opt/3table_index.md'
    - 'L4 查询优化': 'chap2_opt/4table_query.md'
    - 'L5 高可用架构 - MySQL 复制': 'chap2_opt/5db_perf_replica.md'
    - 'L6 MySQL高可用架构': 'chap2_opt/6db_ha.md'
    - 'L7 分布式架构篇': 'chap2_opt/7Dist_db.md'
    - 'L8 Operation Interview': 'chap2_opt/8opt_int.md'
  - 'AWS Aurora 技术与实战教程':
    - '第一节 深入了解 Aurora 数据库' : 'aurora/1Intital_Explore.md'
    - '第二节 揭秘 Aurora 底层存储' : 'aurora/2Aurora_Adv.md'
    - '第三节 Aurora Basic Operation' : 'aurora/3Aurora_operation.md'
  - 'MySQL on K8S':
    - '第一节 Kubernetes 部署 MySQL 主从服务': 'chap_k8s/1Mysql_k8s.md'
  - 'MySQL 基础操作篇':
    - '第一节 数据库简介、及常用数据库介绍': 'db_ops/1db_intro.md'
    - '第二节 安装 MySQL Repository & Jam db install': 'db_ops/2db_install.md'
    - '第三节 结构化查询语言 SQL': 'db_ops/3db_sql.md'
    - '第四节 MySQL 操作实例(上)': 'db_ops/4db_sql_ops1.md'
    - '第五节 MySQL 操作实例(中)': 'db_ops/5db_sql_ops2.md'
    - '第六节 Mysql操作实例(下)': 'db_ops/6db_sql_ops3.md'
    - '第七节 MySQL 数据类型约束': 'db_ops/7db_type.md'
    - '第八节 MySQL 索引': 'db_ops/8db_index.md'
    - '第九节 MySQL 的用户管理和权限管理': 'db_ops/9db_mgt.md'
    - '第十节 MySQL 日志管理': 'db_ops/10db_logs.md'
    - '第十一节 MySQL备份概述': 'db_ops/11db_backup.md'
    - '第十二节 MySQL逻辑备份mysqldump': 'db_ops/13db_xtrabackup.md'
    - '第十四节 MySQL 主从复制原理介绍': 'db_ops/14mysql_replicate.md'
    - '第十五节 MySQL 传统主从同步配置': 'db_ops/15mysql_master_slave.md'
    - '第十六节 MySQL 基于 GTID 的主从复制': 'db_ops/16mysq_gtid.md'
    - 'Mysql OPS Review': 'db_ops/17ops_review.md'
    - 'SQL操作精简版': 'db_ops/18review_short.md'
  - 'MongoDB 实战教程':
    - '1 MongoDB介绍': 'mongo1/1mongodb_intro.md'
    - '2 MongoDB 快速安装': 'mongo1/2mongodb_install.md'
    - '3 在 Kubernetes 上编排 MongoDB 集群': 'mongo1/3mongodb_k8s_cluster.md'
    - '4 MongoDB文档操作': 'mongo1/4mongodb_opt.md'
    - '5 MongoDB整合SpringBoot': 'mongo1/5mongodb_springbboot.md'
    - '6 MongoDB 聚合操作': 'mongo1/6mongodb_pip.md'
    - '7 MongoDB聚合操作高级操作': 'mongo1/7mongodb_pip2.md'
    - '8 MongoDB视图': 'mongo1/8mongodb_view.md'
    - '9 MongoDB索引': 'mongo1/9mongodb_index.md'
  - 'Extra 知识扩展':
    - 'GitHub+Travis+Mkdocs自动化构建文档库(DataBase)' : 'extra/mkdoc_gitbook.md'

repo_url: https://github.com/Chao-Xi/jxdatabasebook.git
repo_name: "jxdatabasebook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'red'
  i18n:
    prev: 'Previous'
    next: 'Next'