site_name: Jacob DataBase Book
site_description: "Jacob's Database 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'MySQL 基础篇':
    - '第一节 基础架构：执行一条SQL查询语句' : 'chap1/1mysql_exec.md'
    - '第二节 日志系统：执行一条SQL更新语句' : 'chap1/2mysql_logs.md'
    - '第三节 事务隔离' : 'chap1/3mysql_isolaion.md'
    - '第四节 深入浅出索引' : 'chap1/4mysql_index.md'
    - '第五节 全局锁和表锁' : 'chap1/5mysql_lock.md'
    - '第六节 事务到底是隔离的还是不隔离的' : 'chap1/6mysql_transaction_isolation.md'
    - 'MySQL 基础知识复习': 'chap1/mysql_bia_review.md'
  - 'MySQL 实战篇':
    - 'L1 表结构设计篇 - 数据类型': 'chap2_opt/1table_design.md'
    - 'L2 表结构设计篇 - 表设计': 'chap2_opt/2table_design.md'
    - 'L3 索引优化': 'chap2_opt/3table_index.md'
    - 'L4 查询优化': 'chap2_opt/4table_query.md'
    - 'L5 高可用架构 - MySQL 复制': 'chap2_opt/5db_perf_replica.md'
    - 'L6 MySQL高可用架构': 'chap2_opt/6db_ha.md'
    - 'L7 分布式架构篇': 'chap2_opt/7Dist_db.md'
    - 'L8 Operation Interview': 'chap2_opt/8opt_int.md'
  - 'AWS Aurora 技术与实战教程':
    - '第一节 深入了解 Aurora 数据库' : 'aurora/1Intital_Explore.md'
    - '第二节 揭秘 Aurora 底层存储' : 'aurora/2Aurora_Adv.md'
    - '第三节 Aurora Basic Operation' : 'aurora/3Aurora_operation.md'
  - 'MySQL on K8S':
    - '第一节 Kubernetes 部署 MySQL 主从服务': 'chap_k8s/1Mysql_k8s.md'
  - 'MySQL 基础操作篇':
    - '第一节 数据库简介、及常用数据库介绍': 'db_ops/1db_intro.md'
    - '第二节 安装 MySQL Repository & Jam db install': 'db_ops/2db_install.md'
    - '第三节 结构化查询语言 SQL': 'db_ops/3db_sql.md'
    - '第四节 MySQL 操作实例(上)': 'db_ops/4db_sql_ops1.md'
    - '第五节 MySQL 操作实例(中)': 'db_ops/5db_sql_ops2.md'
    - '第六节 Mysql操作实例(下)': 'db_ops/6db_sql_ops3.md'
    - '第七节 MySQL 数据类型约束': 'db_ops/7db_type.md'
    - '第八节 MySQL 索引': 'db_ops/8db_index.md'
    - '第九节 MySQL 的用户管理和权限管理': 'db_ops/9db_mgt.md'
    - '第十节 MySQL 日志管理': 'db_ops/10db_logs.md'
    - '第十一节 MySQL备份概述': 'db_ops/11db_backup.md'
    - '第十二节 MySQL逻辑备份mysqldump': 'db_ops/13db_xtrabackup.md'
    - '第十四节 MySQL 主从复制原理介绍': 'db_ops/14mysql_replicate.md'
    - '第十五节 MySQL 传统主从同步配置': 'db_ops/15mysql_master_slave.md'
    - '第十六节 MySQL 基于 GTID 的主从复制': 'db_ops/16mysq_gtid.md'
    - 'Mysql OPS Review': 'db_ops/17ops_review.md'
    - 'SQL操作精简版': 'db_ops/18review_short.md'
  - 'MongoDB 操作实战教程':
    - '1 MongoDB介绍': 'mongo1/1mongodb_intro.md'
    - '2 MongoDB 快速安装': 'mongo1/2mongodb_install.md'
    - '3 在 Kubernetes 上编排 MongoDB 集群': 'mongo1/3mongodb_k8s_cluster.md'
    - '4 MongoDB文档操作': 'mongo1/4mongodb_opt.md'
    - '5 MongoDB整合SpringBoot': 'mongo1/5mongodb_springbboot.md'
    - '6 MongoDB 聚合操作': 'mongo1/6mongodb_pip.md'
    - '7 MongoDB聚合操作高级操作': 'mongo1/7mongodb_pip2.md'
    - '8 MongoDB视图': 'mongo1/8mongodb_view.md'
    - '9 MongoDB索引': 'mongo1/9mongodb_index.md'
    - '10 索引属性': 'mongo1/10mongodb_index_adv.md'
    - '11 explain执行计划详解': 'mongo1/11mongodb_explain.md'
  - 'MongoDB 高级实战教程(全)':
    - '1 认识文档数据库 MongoDB & 及数据安装' : 'mongo2/1mon_intro_install.md'
    - '2 MongoDB 基本操作及聚合操作实战' : 'mongo2/2mon_command.md'
    - '3 复制集机制及原理 & 实现': 'mongo2/3mon_rep.md'
    - '4 MongoDB 全家桶': 'mongo2/4mon_tools.md'
    - '5 Mongo 模型设计': 'mongo2/5mon_design.md'
    - '6 MongoDB 事务开发': 'mongo2/6mon_red_write.md'
    - '7 MongoDB Change Stream & 开发最佳实践': 'mongo2/7mon_changestream_bestdesign.md'
    - '8 Mongo Shards分片技术': 'mongo2/8mon_shard.md'
    - '9 MongoDB 监控最佳实践': 'mongo2/9mon_monitor.md'
    - '10 MongoDB 备份与恢复': 'mongo2/10mon_bakup_restore.md'
    - '11 MongoDB 安全设计': 'mongo2/11mon_sec.md'
    - '12 MongoDB 索引': 'mongo2/12mon_index.md'
    - '13 MongoDB 性能': 'mongo2/13mon_perf.md'
    - '14 高级集群设计': 'mongo2/14mon_cluster.md'
    - '15 MongoDB上线及升级': 'mongo2/15mon_goonline.md'
    - '16 MongoDB 应用实例和场景': 'mongo2/16mon_sample.md'
    - '17 数据迁移': 'mongo2/17mon_dms.md'
    - '18 MongoDB + Spark实战': 'mongo2/18mon_spark.md'
    - '19 MongoDB SQL 套接件': 'mongo2/19mon_sql.md'
    - '20 MongoDB 与微服务 & 数据中台': 'mongo2/20MongoDB_mico_middle_service.md'
  - 'PostgresSQL 12.6运维入门':
    - '1 PostgreSQL介绍&安装&链接管理&用户权限管理': 'pg1/2pg_intall.md'
    - '2 常用基础命令介绍': 'pg1/3pg_cmd.md'
    - '3 Online WAL[Write Head Log]日志（redo)': 'pg1/4pg_logs.md'
    - '4 体系结构介绍': 'pg1/4pg_stru.md'
    - '5 备份恢复恢复': 'pg1/5pg_bak.md'
    - '6 Master-Slave流复制': 'pg1/6pg_repl.md'
    - '7 有用的系统函数': 'pg1/7pg_ops.md'
    - 'PostgreSQL Interview Questions 2022': 'pg1/1pg_int.md'
  - 'AWS DB OTHERs':
    - 'L1 深入了解 Amazon Neptune 图数据库技术': 'aws/1aws_neptune.md'
    - 'L2 分布式键值存储 Dynamo 的实现原理': 'aws/2dydb1.md'
  - 'Extra 知识扩展':
    - 'GitHub+Travis+Mkdocs自动化构建文档库(DataBase)' : 'extra/mkdoc_gitbook.md'

repo_url: https://github.com/Chao-Xi/jxdatabasebook.git
repo_name: "jxdatabasebook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'red'
  i18n:
    prev: 'Previous'
    next: 'Next'