site_name: Jacob DataBase Book
site_description: "Jacob's Database 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"

repo_url: https://github.com/Chao-Xi/jxdatabasebook.git
repo_name: "jxdatabasebook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'red'
    accent: 'red'
  i18n:
    prev: 'Previous'
    next: 'Next'